/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CareerStream = { 'contentGaming' : null } |
  { 'arts' : null } |
  { 'commerce' : null } |
  { 'science' : null };
export interface Milestone {
  'title' : string,
  'year' : bigint,
  'description' : string,
  'actions' : Array<string>,
  'skills' : Array<string>,
}
export interface QuizAnswer { 'questionId' : bigint, 'selectedOption' : bigint }
export interface QuizResult {
  'completedAt' : Timestamp,
  'answers' : Array<QuizAnswer>,
  'recommendedStream' : CareerStream,
}
export interface RoadmapPublic {
  'stream' : CareerStream,
  'userId' : UserId,
  'updatedAt' : Timestamp,
  'milestones' : Array<Milestone>,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StreamProgressPublic {
  'completedQuizzes' : Array<bigint>,
  'stream' : CareerStream,
  'completedMicroProjects' : Array<bigint>,
  'lastUpdated' : Timestamp,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface SubscriptionStatusPublic {
  'expiresAt' : [] | [Timestamp],
  'stripeSubscriptionId' : [] | [string],
  'userId' : UserId,
  'tier' : SubscriptionTier,
  'updatedAt' : Timestamp,
  'stripeCustomerId' : [] | [string],
}
export type SubscriptionTier = { 'premium' : null } |
  { 'free' : null };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfilePublic {
  'userId' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'activeStream' : [] | [CareerStream],
  'quizResult' : [] | [QuizResult],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'activatePremiumSubscription' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelMySubscription' : ActorMethod<[], undefined>,
  'checkIsPremium' : ActorMethod<[], boolean>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createSubscriptionCheckout' : ActorMethod<[string, string], string>,
  'generateDefaultRoadmap' : ActorMethod<[CareerStream], undefined>,
  'getAllMyProgress' : ActorMethod<[], Array<StreamProgressPublic>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyProgress' : ActorMethod<[CareerStream], [] | [StreamProgressPublic]>,
  'getMyRoadmap' : ActorMethod<[], [] | [RoadmapPublic]>,
  'getMySubscriptionStatus' : ActorMethod<[], SubscriptionStatusPublic>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'markMicroProjectCompleted' : ActorMethod<[CareerStream, bigint], undefined>,
  'markQuizCompleted' : ActorMethod<[CareerStream, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[string], undefined>,
  'saveQuizResult' : ActorMethod<[QuizResult], undefined>,
  'saveRoadmap' : ActorMethod<[CareerStream, Array<Milestone>], undefined>,
  'setActiveStream' : ActorMethod<[CareerStream], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateRoadmapMilestones' : ActorMethod<[Array<Milestone>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];