/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const CareerStream = IDL.Variant({
  'contentGaming' : IDL.Null,
  'arts' : IDL.Null,
  'commerce' : IDL.Null,
  'science' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const StreamProgressPublic = IDL.Record({
  'completedQuizzes' : IDL.Vec(IDL.Nat),
  'stream' : CareerStream,
  'completedMicroProjects' : IDL.Vec(IDL.Nat),
  'lastUpdated' : Timestamp,
});
export const UserId = IDL.Principal;
export const QuizAnswer = IDL.Record({
  'questionId' : IDL.Nat,
  'selectedOption' : IDL.Nat,
});
export const QuizResult = IDL.Record({
  'completedAt' : Timestamp,
  'answers' : IDL.Vec(QuizAnswer),
  'recommendedStream' : CareerStream,
});
export const UserProfilePublic = IDL.Record({
  'userId' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'activeStream' : IDL.Opt(CareerStream),
  'quizResult' : IDL.Opt(QuizResult),
});
export const Milestone = IDL.Record({
  'title' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'actions' : IDL.Vec(IDL.Text),
  'skills' : IDL.Vec(IDL.Text),
});
export const RoadmapPublic = IDL.Record({
  'stream' : CareerStream,
  'userId' : UserId,
  'updatedAt' : Timestamp,
  'milestones' : IDL.Vec(Milestone),
});
export const SubscriptionTier = IDL.Variant({
  'premium' : IDL.Null,
  'free' : IDL.Null,
});
export const SubscriptionStatusPublic = IDL.Record({
  'expiresAt' : IDL.Opt(Timestamp),
  'stripeSubscriptionId' : IDL.Opt(IDL.Text),
  'userId' : UserId,
  'tier' : SubscriptionTier,
  'updatedAt' : Timestamp,
  'stripeCustomerId' : IDL.Opt(IDL.Text),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'activatePremiumSubscription' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelMySubscription' : IDL.Func([], [], []),
  'checkIsPremium' : IDL.Func([], [IDL.Bool], ['query']),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createSubscriptionCheckout' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'generateDefaultRoadmap' : IDL.Func([CareerStream], [], []),
  'getAllMyProgress' : IDL.Func([], [IDL.Vec(StreamProgressPublic)], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyProgress' : IDL.Func(
      [CareerStream],
      [IDL.Opt(StreamProgressPublic)],
      ['query'],
    ),
  'getMyRoadmap' : IDL.Func([], [IDL.Opt(RoadmapPublic)], ['query']),
  'getMySubscriptionStatus' : IDL.Func(
      [],
      [SubscriptionStatusPublic],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markMicroProjectCompleted' : IDL.Func([CareerStream, IDL.Nat], [], []),
  'markQuizCompleted' : IDL.Func([CareerStream, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
  'saveQuizResult' : IDL.Func([QuizResult], [], []),
  'saveRoadmap' : IDL.Func([CareerStream, IDL.Vec(Milestone)], [], []),
  'setActiveStream' : IDL.Func([CareerStream], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateRoadmapMilestones' : IDL.Func([IDL.Vec(Milestone)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const CareerStream = IDL.Variant({
    'contentGaming' : IDL.Null,
    'arts' : IDL.Null,
    'commerce' : IDL.Null,
    'science' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const StreamProgressPublic = IDL.Record({
    'completedQuizzes' : IDL.Vec(IDL.Nat),
    'stream' : CareerStream,
    'completedMicroProjects' : IDL.Vec(IDL.Nat),
    'lastUpdated' : Timestamp,
  });
  const UserId = IDL.Principal;
  const QuizAnswer = IDL.Record({
    'questionId' : IDL.Nat,
    'selectedOption' : IDL.Nat,
  });
  const QuizResult = IDL.Record({
    'completedAt' : Timestamp,
    'answers' : IDL.Vec(QuizAnswer),
    'recommendedStream' : CareerStream,
  });
  const UserProfilePublic = IDL.Record({
    'userId' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'activeStream' : IDL.Opt(CareerStream),
    'quizResult' : IDL.Opt(QuizResult),
  });
  const Milestone = IDL.Record({
    'title' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'actions' : IDL.Vec(IDL.Text),
    'skills' : IDL.Vec(IDL.Text),
  });
  const RoadmapPublic = IDL.Record({
    'stream' : CareerStream,
    'userId' : UserId,
    'updatedAt' : Timestamp,
    'milestones' : IDL.Vec(Milestone),
  });
  const SubscriptionTier = IDL.Variant({
    'premium' : IDL.Null,
    'free' : IDL.Null,
  });
  const SubscriptionStatusPublic = IDL.Record({
    'expiresAt' : IDL.Opt(Timestamp),
    'stripeSubscriptionId' : IDL.Opt(IDL.Text),
    'userId' : UserId,
    'tier' : SubscriptionTier,
    'updatedAt' : Timestamp,
    'stripeCustomerId' : IDL.Opt(IDL.Text),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'activatePremiumSubscription' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelMySubscription' : IDL.Func([], [], []),
    'checkIsPremium' : IDL.Func([], [IDL.Bool], ['query']),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createSubscriptionCheckout' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'generateDefaultRoadmap' : IDL.Func([CareerStream], [], []),
    'getAllMyProgress' : IDL.Func(
        [],
        [IDL.Vec(StreamProgressPublic)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyProgress' : IDL.Func(
        [CareerStream],
        [IDL.Opt(StreamProgressPublic)],
        ['query'],
      ),
    'getMyRoadmap' : IDL.Func([], [IDL.Opt(RoadmapPublic)], ['query']),
    'getMySubscriptionStatus' : IDL.Func(
        [],
        [SubscriptionStatusPublic],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markMicroProjectCompleted' : IDL.Func([CareerStream, IDL.Nat], [], []),
    'markQuizCompleted' : IDL.Func([CareerStream, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
    'saveQuizResult' : IDL.Func([QuizResult], [], []),
    'saveRoadmap' : IDL.Func([CareerStream, IDL.Vec(Milestone)], [], []),
    'setActiveStream' : IDL.Func([CareerStream], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateRoadmapMilestones' : IDL.Func([IDL.Vec(Milestone)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };