/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface StreamProgressPublic {
    completedQuizzes: Array<bigint>;
    stream: CareerStream;
    completedMicroProjects: Array<bigint>;
    lastUpdated: Timestamp;
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface RoadmapPublic {
    stream: CareerStream;
    userId: UserId;
    updatedAt: Timestamp;
    milestones: Array<Milestone>;
}
export interface QuizAnswer {
    questionId: bigint;
    selectedOption: bigint;
}
export interface QuizResult {
    completedAt: Timestamp;
    answers: Array<QuizAnswer>;
    recommendedStream: CareerStream;
}
export interface SubscriptionStatusPublic {
    expiresAt?: Timestamp;
    stripeSubscriptionId?: string;
    userId: UserId;
    tier: SubscriptionTier;
    updatedAt: Timestamp;
    stripeCustomerId?: string;
}
export interface Milestone {
    title: string;
    year: bigint;
    description: string;
    actions: Array<string>;
    skills: Array<string>;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface UserProfilePublic {
    userId: UserId;
    name: string;
    createdAt: Timestamp;
    activeStream?: CareerStream;
    quizResult?: QuizResult;
}
export type UserId = Principal;
export interface http_header {
    value: string;
    name: string;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export enum CareerStream {
    contentGaming = "contentGaming",
    arts = "arts",
    commerce = "commerce",
    science = "science"
}
export enum SubscriptionTier {
    premium = "premium",
    free = "free"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    activatePremiumSubscription(stripeCustomerId: string, stripeSubscriptionId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelMySubscription(): Promise<void>;
    checkIsPremium(): Promise<boolean>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createSubscriptionCheckout(successUrl: string, cancelUrl: string): Promise<string>;
    generateDefaultRoadmap(stream: CareerStream): Promise<void>;
    getAllMyProgress(): Promise<Array<StreamProgressPublic>>;
    getCallerUserProfile(): Promise<UserProfilePublic | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyProgress(stream: CareerStream): Promise<StreamProgressPublic | null>;
    getMyRoadmap(): Promise<RoadmapPublic | null>;
    getMySubscriptionStatus(): Promise<SubscriptionStatusPublic>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    markMicroProjectCompleted(stream: CareerStream, projectId: bigint): Promise<void>;
    markQuizCompleted(stream: CareerStream, quizId: bigint): Promise<void>;
    saveCallerUserProfile(name: string): Promise<void>;
    saveQuizResult(result: QuizResult): Promise<void>;
    saveRoadmap(stream: CareerStream, milestones: Array<Milestone>): Promise<void>;
    setActiveStream(stream: CareerStream): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateRoadmapMilestones(milestones: Array<Milestone>): Promise<void>;
}
import type { CareerStream as _CareerStream, Milestone as _Milestone, QuizAnswer as _QuizAnswer, QuizResult as _QuizResult, RoadmapPublic as _RoadmapPublic, StreamProgressPublic as _StreamProgressPublic, StripeSessionStatus as _StripeSessionStatus, SubscriptionStatusPublic as _SubscriptionStatusPublic, SubscriptionTier as _SubscriptionTier, Timestamp as _Timestamp, UserId as _UserId, UserProfilePublic as _UserProfilePublic, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async activatePremiumSubscription(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activatePremiumSubscription(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activatePremiumSubscription(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelMySubscription(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelMySubscription();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelMySubscription();
            return result;
        }
    }
    async checkIsPremium(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkIsPremium();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkIsPremium();
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createSubscriptionCheckout(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubscriptionCheckout(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubscriptionCheckout(arg0, arg1);
            return result;
        }
    }
    async generateDefaultRoadmap(arg0: CareerStream): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.generateDefaultRoadmap(to_candid_CareerStream_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateDefaultRoadmap(to_candid_CareerStream_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllMyProgress(): Promise<Array<StreamProgressPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMyProgress();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMyProgress();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProgress(arg0: CareerStream): Promise<StreamProgressPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProgress(to_candid_CareerStream_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProgress(to_candid_CareerStream_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRoadmap(): Promise<RoadmapPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRoadmap();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRoadmap();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySubscriptionStatus(): Promise<SubscriptionStatusPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySubscriptionStatus();
                return from_candid_SubscriptionStatusPublic_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySubscriptionStatus();
            return from_candid_SubscriptionStatusPublic_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async markMicroProjectCompleted(arg0: CareerStream, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMicroProjectCompleted(to_candid_CareerStream_n3(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMicroProjectCompleted(to_candid_CareerStream_n3(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async markQuizCompleted(arg0: CareerStream, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markQuizCompleted(to_candid_CareerStream_n3(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markQuizCompleted(to_candid_CareerStream_n3(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveQuizResult(arg0: QuizResult): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveQuizResult(to_candid_QuizResult_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveQuizResult(to_candid_QuizResult_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveRoadmap(arg0: CareerStream, arg1: Array<Milestone>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveRoadmap(to_candid_CareerStream_n3(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveRoadmap(to_candid_CareerStream_n3(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async setActiveStream(arg0: CareerStream): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setActiveStream(to_candid_CareerStream_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setActiveStream(to_candid_CareerStream_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateRoadmapMilestones(arg0: Array<Milestone>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRoadmapMilestones(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRoadmapMilestones(arg0);
            return result;
        }
    }
}
function from_candid_CareerStream_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CareerStream): CareerStream {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_QuizResult_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuizResult): QuizResult {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_RoadmapPublic_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoadmapPublic): RoadmapPublic {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_StreamProgressPublic_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StreamProgressPublic): StreamProgressPublic {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatusPublic_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatusPublic): SubscriptionStatusPublic {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionTier_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionTier): SubscriptionTier {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CareerStream]): CareerStream | null {
    return value.length === 0 ? null : from_candid_CareerStream_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QuizResult]): QuizResult | null {
    return value.length === 0 ? null : from_candid_QuizResult_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StreamProgressPublic]): StreamProgressPublic | null {
    return value.length === 0 ? null : from_candid_StreamProgressPublic_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RoadmapPublic]): RoadmapPublic | null {
    return value.length === 0 ? null : from_candid_RoadmapPublic_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _UserId;
    name: string;
    createdAt: _Timestamp;
    activeStream: [] | [_CareerStream];
    quizResult: [] | [_QuizResult];
}): {
    userId: UserId;
    name: string;
    createdAt: Timestamp;
    activeStream?: CareerStream;
    quizResult?: QuizResult;
} {
    return {
        userId: value.userId,
        name: value.name,
        createdAt: value.createdAt,
        activeStream: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.activeStream)),
        quizResult: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.quizResult))
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedAt: _Timestamp;
    answers: Array<_QuizAnswer>;
    recommendedStream: _CareerStream;
}): {
    completedAt: Timestamp;
    answers: Array<QuizAnswer>;
    recommendedStream: CareerStream;
} {
    return {
        completedAt: value.completedAt,
        answers: value.answers,
        recommendedStream: from_candid_CareerStream_n8(_uploadFile, _downloadFile, value.recommendedStream)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stream: _CareerStream;
    userId: _UserId;
    updatedAt: _Timestamp;
    milestones: Array<_Milestone>;
}): {
    stream: CareerStream;
    userId: UserId;
    updatedAt: Timestamp;
    milestones: Array<Milestone>;
} {
    return {
        stream: from_candid_CareerStream_n8(_uploadFile, _downloadFile, value.stream),
        userId: value.userId,
        updatedAt: value.updatedAt,
        milestones: value.milestones
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expiresAt: [] | [_Timestamp];
    stripeSubscriptionId: [] | [string];
    userId: _UserId;
    tier: _SubscriptionTier;
    updatedAt: _Timestamp;
    stripeCustomerId: [] | [string];
}): {
    expiresAt?: Timestamp;
    stripeSubscriptionId?: string;
    userId: UserId;
    tier: SubscriptionTier;
    updatedAt: Timestamp;
    stripeCustomerId?: string;
} {
    return {
        expiresAt: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.expiresAt)),
        stripeSubscriptionId: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.stripeSubscriptionId)),
        userId: value.userId,
        tier: from_candid_SubscriptionTier_n27(_uploadFile, _downloadFile, value.tier),
        updatedAt: value.updatedAt,
        stripeCustomerId: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.stripeCustomerId))
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedQuizzes: Array<bigint>;
    stream: _CareerStream;
    completedMicroProjects: Array<bigint>;
    lastUpdated: _Timestamp;
}): {
    completedQuizzes: Array<bigint>;
    stream: CareerStream;
    completedMicroProjects: Array<bigint>;
    lastUpdated: Timestamp;
} {
    return {
        completedQuizzes: value.completedQuizzes,
        stream: from_candid_CareerStream_n8(_uploadFile, _downloadFile, value.stream),
        completedMicroProjects: value.completedMicroProjects,
        lastUpdated: value.lastUpdated
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    premium: null;
} | {
    free: null;
}): SubscriptionTier {
    return "premium" in value ? SubscriptionTier.premium : "free" in value ? SubscriptionTier.free : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n31(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contentGaming: null;
} | {
    arts: null;
} | {
    commerce: null;
} | {
    science: null;
}): CareerStream {
    return "contentGaming" in value ? CareerStream.contentGaming : "arts" in value ? CareerStream.arts : "commerce" in value ? CareerStream.commerce : "science" in value ? CareerStream.science : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StreamProgressPublic>): Array<StreamProgressPublic> {
    return value.map((x)=>from_candid_StreamProgressPublic_n6(_uploadFile, _downloadFile, x));
}
function to_candid_CareerStream_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CareerStream): _CareerStream {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_QuizResult_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuizResult): _QuizResult {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedAt: Timestamp;
    answers: Array<QuizAnswer>;
    recommendedStream: CareerStream;
}): {
    completedAt: _Timestamp;
    answers: Array<_QuizAnswer>;
    recommendedStream: _CareerStream;
} {
    return {
        completedAt: value.completedAt,
        answers: value.answers,
        recommendedStream: to_candid_CareerStream_n3(_uploadFile, _downloadFile, value.recommendedStream)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CareerStream): {
    contentGaming: null;
} | {
    arts: null;
} | {
    commerce: null;
} | {
    science: null;
} {
    return value == CareerStream.contentGaming ? {
        contentGaming: null
    } : value == CareerStream.arts ? {
        arts: null
    } : value == CareerStream.commerce ? {
        commerce: null
    } : value == CareerStream.science ? {
        science: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
